version: '3'
services:
  web:
    container_name: web-php
    image: php:7.2-apache
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
      - ./conf:/usr/local/etc/php